<?php

$sql = "CREATE TABLE users (id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(20) UNIQUE NOT NULL, password VARCHAR(60) NOT NULL, level FLOAT UNSIGNED NOT NULL,avatar VARCHAR(30),in_guild INTEGER UNSIGNED,header_guild TINYINT, result_id INTEGER UNSIGNED, FOREIGN KEY (result_id) REFERENCES results(id),date TIMESTAMP NOT NULL)";

return $sql;
